---
page-layout: custom
section-divs: false
sidebar: false
search: false
---


<style>

:root {
  --container-bg-color: rgb(78, 78, 78);
  --left-bg-color: rgba(232,238,240, 0.6);
  --left-button-hover-color: rgba(161, 11, 11, 0.3);
  --right-bg-color: rgba(130, 90, 64, 0.6);
  --right-button-hover-color: rgba(92, 92, 92, 0.3);
  --hover-width: 75%;
  --other-width: 25%;
  --speed: 1000ms;
}

.split.left .button:hover {
  background-color: var(--left-button-hover-color);
  border-color: var(--left-button-hover-color);
}

.split.right .button:hover {
  background-color: var(--right-button-hover-color);
  border-color: var(--right-button-hover-color);
}

.container {
  position: absolute;
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  background: var(--container-bg-color);
}

.split {
  position: absolute;
  width: 50%;
  height: 100%;
  overflow: hidden;
}

.split.left {
  left:0;
  background: url('./asset/left.jpg') center center no-repeat;
  background-size: cover;
  filter: blur(3px);
  -webkit-filter: blur(3px);
}

.split.left:before {
  position:absolute;
  content: "";
  width: 100%;
  height: 100%;
  background: var(--left-bg-color);
}

.split.right {
  right:0;
  background: url('./asset/right.jpg') center center no-repeat;
  background-size: cover;
  filter: blur(3px);
  -webkit-filter: blur(3px);
}

.split.right:before {
  position:absolute;
  content: "";
  width: 100%;
  height: 100%;
  background: var(--right-bg-color);
}

.split.left, .split.right, .split.right:before, .split.left:before {
  transition: var(--speed) all ease-in-out;
}

.hover-left .left {
  width: var(--hover-width);
}

.hover-left .right {
  width: var(--other-width);
}

.hover-left .right:before {
  z-index: 2;
}

.hover-right .right {
  width: var(--hover-width);
}

.hover-right .left {
  width: var(--other-width);
}

.hover-right .left:before {
  z-index: 2;
}

.nav-footer .nav-footer-left {
    position: relative;
    z-index: 1;
}

.nav-footer .nav-footer-center {
    position: relative;
    z-index: 1;
}

.nav-footer .nav-footer-right {
    position: relative;
    z-index: 1;
}

</style>


<div class="container">
  <div class="split left">
  </div>
  <div class="split right">
  </div>
</div>


<script>

const left = document.querySelector(".left");
const right = document.querySelector(".right");
const container = document.querySelector(".container");

left.addEventListener("mouseenter", () => {
  container.classList.add("hover-left");
});

left.addEventListener("mouseleave", () => {
  container.classList.remove("hover-left");
});

right.addEventListener("mouseenter", () => {
  container.classList.add("hover-right");
});

right.addEventListener("mouseleave", () => {
  container.classList.remove("hover-right");
});

</script>














